version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=your_elastic_password
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - ES_JAVA_OPTS=-Xms2g -Xmx2g  # Adjust the heap size
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-net
    deploy:
      resources:
        limits:
          memory: 4g  # Adjust memory limit
        reservations:
          memory: 1g  # Ensure at least this much memory is reserved
  dev:
    build:
      context: .
    depends_on:
      - elasticsearch
    env_file:
      - .env
    volumes:
      - ./models:/srv/models
      - ./src:/srv/src
    container_name: app
    networks:
      - es-net
volumes:
  es-data:
    driver: local

networks:
  es-net:
    driver: bridge
